name: CI

on:
  push:
    branches: [ "20.x" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

      - name: Upload coverage report
        if: always()   
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
          if-no-files-found: warn
          compression-level: 6
          overwrite: true       
          include-hidden-files: false
